---
- name: Deploy novo servidor no vcenter com imagme do imagebuilder
  hosts: localhost
  gather_facts: false
  vars_files:
    - informacoes_sensiveis.txt
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: Criando um servidor atraves do template do Vcenter
      vmware.vmware.deploy_folder_template:
        hostname: "{{ endereco_vcenter }}"
        username: "{{ usuario_vcenter }}"
        password: "{{ senha_vcenter }}"
        datacenter: "{{ datacenter_vcenter }}"
        vm_name: "{{ servidorsn }}.{{ dominio }}"
        template_name: "{{ template_vcenter }}"
        validate_certs: false
        cluster: "{{ cluster_das_vms }}"
        vm_folder: "{{ diretorio_vcenter }}"
        power_on_after_deploy: false

    - name: Altera a interface da VM para portforce
      vmware.vmware.vm:
        hostname: "{{ endereco_vcenter }}"
        username: "{{ usuario_vcenter }}"
        password: "{{ senha_vcenter }}"
        datacenter: "{{ datacenter_vcenter }}"
        validate_certs: false
        name: "{{ servidorsn }}.{{ dominio }}"
        network_adapters:
          - network: "{{ rede_vmware }}"

    - name: Liga a VM
      vmware.vmware.vm_powerstate:
        hostname: "{{ endereco_vcenter }}"
        username: "{{ usuario_vcenter }}"
        password: "{{ senha_vcenter }}"
        datacenter: "{{ datacenter_vcenter }}"
        validate_certs: false
        folder: "{{ diretorio_vcenter }}"
        name: "{{ servidorsn }}.{{ dominio }}"
        state: powered-on
   
    - name: Coleta as informações da VM recém criada
      until:
        - informacoes_vm.guests[0].ipv4 is defined
        - informacoes_vm.guests[0].ipv4 is not none
      retries: 99
      delay: 1
      vmware.vmware.guest_info:
        hostname: "{{ endereco_vcenter }}"
        username: "{{ usuario_vcenter }}"
        password: "{{ senha_vcenter }}"
        guest_name: "{{ servidorsn }}.{{ dominio }}"
        validate_certs: false
      register: informacoes_vm

    - name: Define a variável com o IP da máquina
      ansible.builtin.set_fact:
        ip_servidor: "{{ informacoes_vm.guests[0].ipv4 }}"

    - name: Adicionando o {{ servidorsn }} a um inventario dinamico no ansible
      ansible.builtin.add_host:
        name: "{{ servidorsn }}.{{ dominio }}"
        groups: just_created

- name: Adiciona entrada no DNS
  hosts: idm.nests.local
  gather_facts: false
  vars:
    ansible_user: root
    ansible_password: '12345678'
  tasks:
    - name: Autentica no domínio
      ansible.builtin.shell: echo 'redhat@123' | kinit admin
      no_log: true

    - name: Adiciona a máquina no DNS
      failed_when: false
      ansible.builtin.command: ipa dnsrecord-add nests.local. {{ servidorsn }} --a-rec {{ hostvars['localhost'].ip_servidor }}

- name: Registrando servidor {{ servidorsn }} no Satellite
  hosts: just_created
  gather_facts: false
  become: true
  vars_files:
    - informacoes_sensiveis.txt
  tasks:
    - name: Seta o hostname da máquina
      ansible.builtin.hostname:
        name: "{{ servidorsn }}.{{ dominio }}"
        use: systemd

    - name: Obtem o script de registro
      ansible.builtin.uri:
        url: "https://satellite.nests.local/register?activation_keys={{ activation_key }}&download_utility=curl&force=true&location_id=2&organization_id=1&setup_insights=true&setup_remote_execution=true&update_packages=false"
        method: GET
        validate_certs: false
        dest: .
        headers:
          Authorization: Bearer {{ token_satellite }}
      register: saida_satellite

    - name: Registrado no Satelite
      ansible.builtin.command:
        cmd: "bash {{ saida_satellite.path }}"

    - name: Registra máquina no IdM
      vars:
        ipaclient_mkhomedir: true
      ansible.builtin.include_role:
        name: freeipa.ansible_freeipa.ipaclient

    - name: Seta o /etc/hosts corretamente
      ansible.builtin.template:
        src: files/hosts.j2
        dest: /etc/hosts
        mode: '0644'
        owner: root
        group: root

