---
- name: Deploy novo servidor no vcenter com imagme do imagebuilder
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
    servidorsn: vm2
  tasks:
    - name: Criando um servidor atraves do template do Vcenter
      community.vmware.vmware_guest:
        hostname: vcenter.nests.local
        username: administrator@vsphere.local
        password: 'Manchester1!'
        datacenter: meudc
        template: template.nests.local
        folder: provisionadas
        validate_certs: false
        cluster: SuperCluster
        state: poweredon
        name: "{{ servidorsn }}.nests.local"
        networks:
          - name: VM Network
            type: dhcp
        customization:
          hostname: "{{ servidorsn }}.nests.local"
          domain: nests.local
